[package]
name = "unfold-iter"
version = "0.1.1"
edition = "2024"
license = "MIT"
description = "Create iterators with an initial value and a recurrence relation."
documentation = "https://docs.rs/unfold-iter"
repository = "https://github.com/balthild/unfold-iter"

[dependencies]
